### ISSUE TITLE
Retrieving the interaction with UIView

### ISSUE THREAD

**Issue by randcode-generator** [material-motion/material-motion-swift#104]
I would like to get the interaction (draggable) object for a specific UIView. How would I go about getting the interaction (draggable) object based on the UIView?

**Comment by jverkoey** [comment]
One option for an API is: `runtime.interactions(for: view)`, though this wouldn't be able to return a nicely-typed object.

**Comment by jverkoey** [comment]
🎊 My diff is ready for review at http://codereview.cc/D3048
