### ISSUE TITLE
Add explicit time units to operators and interactions

### ISSUE THREAD

**Issue by jverkoey** [material-motion/material-motion-swift#106]
In keeping consistent with Core Animation and UIKit we currently use CGFloat to represent seconds as our canonical time unit.

Swift allows us to be more explicit with our time units and there are examples of nicer time APIs, e.g. [DispatchTimeInterval](https://developer.apple.com/reference/dispatch/dispatchtimeinterval).

```swift
let duration = .seconds(1)
```

The goal of this issue is to introduce new APIs to our operators and interactions that make use of a semantic (complex enum) time unit rather than a purely numerical one.

The following operators and interactions currently make use of time:

- delayBy
- Tween's duration, delay
- Timeline's timeOffset

There are a couple challenges with this change:

1. We're changing existing, stable APIs. If we plan to remove the old APIs then we need to decide on our deprecation plan. We could choose to leave the old APIs and make the new ones be convenience APIs, though this means we're still exposing the old CGFloat-based APIs.
2. Nearly all of our operators think in terms of CGFloat. For example, Tween's `duration` is a `ReactiveProperty<CGFloat>`. This makes it easy to write to or read from a tween's duration using our standard operators. An ideal solution here will still make it easy to use our existing operators will also benefiting from the explicit unit information of an enum-based API.

Caveats:

It doesn't appear that DispatchTimeInterval supports the addition operator, meaning we can't do things like `.seconds(1) + .milliseconds(100)`.

**Comment by appsforartists** [comment]
Done in https://github.com/material-motion/material-motion-swift/commit/ab44321b3906998a72a3a6b544061441179331dd
