### ISSUE TITLE
Can I make draggable with some area offset constraints?

### ISSUE THREAD

**Issue by Amefuri** [material-motion/material-motion-swift#120]
Hi,

After went through some constraints example, I know that I can add some constraints to draggable like this: 

`let draggable = Draggable();
runtime.add(draggable, to: imageView) {
            $0.xLocked(to: 0)
        }`

What I want to do is make this imageView draggable within some area offset.
let's take facebook/twiiter imageViewer for an example, when user scale the image to be larger than a screen size. user will be able to pan the image left/right/up/down but the image will snap its edge to the screen when it reach the end of each edge.

Is anything like this even possible?

Thank you,

**Comment by jverkoey** [comment]
To implement that particular behavior I recommend using a zoomable UIScrollView. This will ensure that all of the system rubber banding and over-scroll behaviors are respected.

**Comment by Amefuri** [comment]
Thank you, I will check with UIScrollView
