### ISSUE TITLE
Ability to remove UIView from runtime

### ISSUE THREAD

**Issue by randcode-generator** [material-motion/material-motion-swift#98]
I would like a function that allows me to remove all features and functionality runtime.add added to my UIView. In another, a function that will make my UIView back to normal.

**Comment by jverkoey** [comment]
Our short-term solution for this may be to ensure that all interactions support being disabled.

**Comment by pingpongboss** [comment]
Yea, this is what I was going to suggest in discord.

**Comment by jverkoey** [comment]
Going to mark this as won't fix for now with the recommendation being to use the `enabled` property on relevant interactions. Please reopen if this isn't sufficient for your use cases.
